Repository sb01-mopl-team03/sb01-mopl-team03, pull requests merged in 2025-07, with the labels that each got.

#50 feat: Spring Batch 를 통한 Content 데이터 적재
  build.gradle
  docker-compose.yml
  src/main/java/team03/mopl/common/config/SchedulingConfig.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/ContentType.java
  src/main/java/team03/mopl/domain/content/batch/common/ApiWriter.java
  src/main/java/team03/mopl/domain/content/batch/common/BatchConfig.java
  src/main/java/team03/mopl/domain/content/batch/job/JobConfig.java
  src/main/java/team03/mopl/domain/content/batch/launcher/InitialDataLoader.java
  src/main/java/team03/mopl/domain/content/batch/launcher/SportsJobScheduler.java
  src/main/java/team03/mopl/domain/content/batch/launcher/TmdbJobScheduler.java
  src/main/java/team03/mopl/domain/content/batch/sports/InitialSportsApiReader.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiReader.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiRequestInfo.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiResponse.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsBatchConfig.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsItemDto.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/InitialTmdbApiReader.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiReader.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiRequestInfo.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiResponse.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbBatchConfig.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbItemDto.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbVideoApiResponse.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbVideoItemDto.java
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
  src/test/java/team03/mopl/domain/chat/service/ChatMessageServiceImplTest.java
  src/test/java/team03/mopl/domain/chat/service/ChatRoomServiceImplTest.java
Labels: enhancement

#51 feat: 카카오 소셜 로그인
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/domain/auth/AuthController.java
  src/main/java/team03/mopl/domain/auth/AuthService.java
  src/main/java/team03/mopl/domain/chat/dto/ChatRoomDto.java
  src/main/java/team03/mopl/domain/oauth2/GoogleOAuthService.java
  src/main/java/team03/mopl/domain/oauth2/KakaoOAuthService.java
  src/main/java/team03/mopl/domain/oauth2/KakaoUserInfo.java
  src/main/java/team03/mopl/domain/oauth2/OAuthController.java
  src/main/java/team03/mopl/domain/oauth2/OAuthLoginService.java
  src/main/java/team03/mopl/domain/user/UserService.java
  src/main/java/team03/mopl/domain/user/UserServiceImpl.java
  src/main/java/team03/mopl/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#52 feat: AI 사용하여 큐레이션 서비스 구현
  build.gradle
  init/schema.sql
  src/main/java/team03/mopl/common/CursorPageResponse.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/service/ContentService.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/dto/KeywordRequest.java
  src/main/java/team03/mopl/domain/curation/dto/KeywordResponse.java
  src/main/java/team03/mopl/domain/curation/entity/Keyword.java
  src/main/java/team03/mopl/domain/curation/entity/KeywordContent.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordContentRepository.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordRepository.java
  src/main/java/team03/mopl/domain/curation/service/CurationService.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/playlist/Playlist.java
  src/test/java/team03/mopl/domain/chat/service/ChatRoomServiceImplTest.java
Labels: enhancement

#53 curation 브랜치명 변경
  init/schema.sql
  src/main/java/team03/mopl/domain/chat/entity/ChatMessage.java
  src/main/java/team03/mopl/domain/content/Content.java
Labels: bug

#55 fix: db 스키마 변경
  init/schema.sql
  src/main/java/team03/mopl/domain/content/Content.java
  src/test/java/team03/mopl/domain/chat/service/ChatRoomServiceImplTest.java
Labels: bug

#58 refactor: 한국어 처리 로직 강화
  build.gradle
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/resources/models/cc.en.300.bin
  src/main/resources/models/cc.ko.300.bin
Labels: enhancement

#57 feat: 실시간 시청방 내 채팅 시스템 구현
  build.gradle
  src/main/java/team03/mopl/common/config/WebSocketConfig.java
  src/main/java/team03/mopl/domain/chat/controller/ChatMessageController.java
  src/main/java/team03/mopl/domain/chat/controller/ChatRoomController.java
  src/main/java/team03/mopl/domain/chat/dto/SystemMessageDto.java
  src/test/java/team03/mopl/common/config/TestSecurityConfig.java
  src/test/java/team03/mopl/domain/chat/controller/ChatMessageControllerTest.java
  src/test/java/team03/mopl/domain/chat/controller/ChatMessageControllerWebSocketTest.java
  src/test/java/team03/mopl/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/team03/mopl/domain/chat/handler/ChatMessageFrameHandler.java
  src/test/java/team03/mopl/domain/chat/handler/TestStompSessionHandler.java
Labels: enhancement

#65 refactor: review 엔티티 builder 패턴으로 변경 및 curation 엔티티 삭제
  src/main/java/team03/mopl/domain/curation/Keyword.java
  src/main/java/team03/mopl/domain/curation/KeywordContent.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
Labels: bug

#66 chore: 사용하지 않는 import문 삭제
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
Labels: bug

#67 feat: 단순 전체 컨텐츠 조회와 단일 컨텐츠 조회 구현
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/domain/content/controller/ContentController.java
  src/main/java/team03/mopl/domain/content/service/ContentService.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/test/java/team03/mopl/domain/content/controller/ContentControllerTest.java
  src/test/java/team03/mopl/domain/content/integration/ContentIntegrationTest.java
  src/test/java/team03/mopl/domain/content/service/ContentServiceImplTest.java
Labels: enhancement

#69 feat: 프로필
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/domain/user/ProfileImageService.java
  src/main/java/team03/mopl/domain/user/User.java
  src/main/java/team03/mopl/domain/user/UserController.java
  src/main/java/team03/mopl/domain/user/UserCreateRequest.java
  src/main/java/team03/mopl/domain/user/UserResponse.java
  src/main/java/team03/mopl/domain/user/UserServiceImpl.java
  src/main/java/team03/mopl/jwt/JwtAuthenticationFilter.java
  src/main/resources/static/profile/buzz.jpeg
  src/main/resources/static/profile/jessie.jpeg
  src/main/resources/static/profile/rex.png
  src/main/resources/static/profile/woody.jpeg
Labels: enhancement

#70 docs: chat -> watch 변경, 유저 profile_image 필드 추가로 인한 schema.sql 수정
  init/schema.sql
  src/main/java/team03/mopl/domain/chat/entity/ChatMessage.java
  src/main/java/team03/mopl/domain/chat/entity/ChatRoom.java
  src/main/java/team03/mopl/domain/chat/entity/ChatRoomParticipant.java
Labels: documentation

#72 chore: test.yml에 최신 커밋 정보 로깅 기능 추가
  .github/workflows/test.yml
Labels: documentation

#73 feature: 공용 페이지네이션 DTO 추가
  src/main/java/team03/mopl/common/CursorPageResponse.java
  src/main/java/team03/mopl/common/dto/Cursor.java
  src/main/java/team03/mopl/common/dto/CursorPageResponseDto.java
Labels: enhancement

#75 feat: review service test, controller test 추가
  src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
  src/test/java/team03/mopl/domain/review/ReviewServiceImplTest.java
Labels: enhancement

#76 feat: curation service test, controller test 추가
  src/main/java/team03/mopl/domain/chat/entity/ChatRoom.java
  src/main/java/team03/mopl/domain/curation/entity/Keyword.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
Labels: enhancement

#79 feat: 커서 페이지네이션 기반 콘텐츠 데이터 조회
  build.gradle
  init/schema.sql
  src/main/java/team03/mopl/common/exception/GlobalExceptionHandler.java
  src/main/java/team03/mopl/common/util/NormalizerUtil.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/SortBy.java
  src/main/java/team03/mopl/domain/content/SortDirection.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiProcessor.java
  src/main/java/team03/mopl/domain/content/controller/ContentController.java
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
  src/main/java/team03/mopl/domain/content/dto/ContentSearchRequest.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepositoryCustom.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepositoryImpl.java
  src/main/java/team03/mopl/domain/content/service/ContentService.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/main/java/team03/mopl/domain/content/validation/AllowedValues.java
  src/main/java/team03/mopl/domain/content/validation/ValueOfValidator.java
  src/test/java/team03/mopl/domain/content/controller/ContentControllerTest.java
  src/test/java/team03/mopl/domain/content/integration/ContentIntegrationTest.java
  src/test/java/team03/mopl/domain/content/repository/ContentRepositoryImplTest.java
  src/test/java/team03/mopl/domain/content/service/ContentServiceImplTest.java
Labels: enhancement

#90 refactor: curation controller 수정 및 CASCADE 설정
  init/schema.sql
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/curation/CurationException.java
  src/main/java/team03/mopl/common/exception/curation/KeywordNotFoundException.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/entity/Keyword.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordContentRepository.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordRepository.java
  src/main/java/team03/mopl/domain/curation/service/CurationService.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/review/entity/Review.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: enhancement

#86 refactor: review controller 수정 및 watchRoomService 수정
  src/main/java/team03/mopl/domain/content/controller/ContentController.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/review/controller/ReviewController.java
  src/main/java/team03/mopl/domain/review/dto/ReviewCreateRequest.java
  src/main/java/team03/mopl/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/team03/mopl/domain/review/service/ReviewService.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
  src/main/java/team03/mopl/domain/user/UserController.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
  src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
  src/test/java/team03/mopl/domain/review/ReviewServiceImplTest.java
Labels: bug

#87 docs: swagger 의존성 추가 및 설정
  build.gradle
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/common/config/SwaggerConfig.java
Labels: documentation

#102 Chore: CD 워크 플로우 작성
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  ecs/task-definition.json
  src/main/resources/application-prod.yaml
Labels: documentation

#105 fix: 프로필
  init/schema.sql
  src/main/java/team03/mopl/common/config/EncoderConfig.java
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/domain/oauth2/CustomOAuth2UserService.java
  src/main/java/team03/mopl/domain/oauth2/GoogleOAuthService.java
  src/main/java/team03/mopl/domain/oauth2/GoogleUserInfo.java
  src/main/java/team03/mopl/domain/oauth2/KakaoOAuthService.java
  src/main/java/team03/mopl/domain/oauth2/KakaoUserInfo.java
  src/main/java/team03/mopl/domain/oauth2/OAuth2SuccessHandler.java
  src/main/java/team03/mopl/domain/oauth2/OAuthController.java
  src/main/java/team03/mopl/domain/oauth2/OAuthLoginService.java
  src/main/java/team03/mopl/domain/user/UserService.java
  src/main/java/team03/mopl/jwt/CustomUserDetails.java
  src/main/java/team03/mopl/jwt/JwtServiceImpl.java
  src/main/java/team03/mopl/jwt/JwtSessionRepository.java
Labels: bug

#107 refactor: keyword delete 메서드에 @AuthenticationPrincipal 추가
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/curation/KeywordDeleteDeniedException.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/service/CurationService.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
Labels: enhancement

#110 fix: 0710 merge 이후 에러 해결
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/domain/subscription/Subscription.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
  src/main/java/team03/mopl/domain/user/UserController.java
  src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
  src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
Labels: bug

#112 fix: test 코드 수정 및 사용하지 않는 CustomUserDetails 파라미터 제거
  src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java
  src/test/java/team03/mopl/domain/watchroom/controller/WatchRoomControllerTest.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: bug

#111 refactor: controller 수정 및 unsubscribe 메서드 수정
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/subscription/NotSubscribedException.java
  src/main/java/team03/mopl/common/exception/subscription/SubscriptionDeleteDeniedException.java
  src/main/java/team03/mopl/common/exception/subscription/SubscriptionNotFoundException.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/review/controller/ReviewController.java
  src/main/java/team03/mopl/domain/subscription/SubscriptionController.java
  src/main/java/team03/mopl/domain/subscription/dto/SubscribeRequest.java
  src/main/java/team03/mopl/domain/subscription/dto/SubscriptionDto.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionService.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
Labels: enhancement

#114 Fix: contents 페이지네이션 일부 수정
  src/main/java/team03/mopl/common/util/NormalizerUtil.java
  src/main/java/team03/mopl/domain/content/dto/ContentSearchRequest.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepositoryImpl.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
Labels: bug

#115 fix: reviewControllerTest 오류 수정
  src/test/java/team03/mopl/domain/review/ReviewControllerTest.java
Labels: bug

#113 fix: 리뷰 중복 작성에 대한 예외처리 추가
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/review/DuplicateReviewException.java
  src/main/java/team03/mopl/domain/review/repository/ReviewRepository.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
Labels: bug

#121 refactor: keywordId 필드 추가
  src/main/java/team03/mopl/domain/curation/dto/KeywordDto.java
Labels: enhancement

#122 fix: s3 읽기 설정
  src/main/java/team03/mopl/storage/S3ProfileStorage.java
Labels: bug

#125 fix: acl 정책 제거, 시큐리티 예외처리
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/storage/S3ProfileStorage.java
Labels: bug

#123 feat: 알림, DM 페이징 로직 구현
  src/main/java/team03/mopl/common/dto/CursorPageResponseDto.java
  src/main/java/team03/mopl/domain/dm/controller/DmController.java
  src/main/java/team03/mopl/domain/dm/dto/DmPagingDto.java
  src/main/java/team03/mopl/domain/dm/entity/Dm.java
  src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java
  src/main/java/team03/mopl/domain/dm/service/DmService.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
  src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationPagingDto.java
  src/main/java/team03/mopl/domain/notification/repository/NotificationRepositoryCustom.java
  src/main/java/team03/mopl/domain/notification/service/EmitterService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/test/java/team03/mopl/domain/dm/controller/DmControllerTest.java
  src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java
  src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java
  src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
Labels: enhancement

#132 fix: playlistDto 변경
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistDto.java
Labels: bug

#130 feature: 알림 삭제 로직 구현 및 테스트 코드 수정
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java
  src/main/java/team03/mopl/domain/notification/repository/NotificationRepository.java
  src/main/java/team03/mopl/domain/notification/service/NotificationService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java
  src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
Labels: enhancement

#131 chore: 다국어 정렬 문제로 문자열 정렬 규칙 집합(Collation) 변경
  init/schema.sql
Labels: documentation

#133 fix: keywordContent @EntityListeners 추가
  src/main/java/team03/mopl/domain/curation/entity/KeywordContent.java
Labels: bug

#137 chore: deploy.yml 누락된 v 추가
  .github/workflows/deploy.yml
Labels: documentation

#140 merge: release 브랜치를 main 브랜치로 머지
  src/main/resources/application-prod.yaml
Labels: documentation

#142 chore: task definition update
  ecs/task-definition.json
Labels: documentation

#148 refactor: 플레이리스트에 콘텐츠 추가하는 방식 수정
  build.gradle
  src/main/java/team03/mopl/common/config/CorsConfig.java
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/GlobalExceptionHandler.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentAlreadyExistsException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentEmptyException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentNotFoundForRemoveException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentRemoveEmptyException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistDeniedException.java
  src/main/java/team03/mopl/domain/dm/controller/DmController.java
  src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
  src/main/java/team03/mopl/domain/notification/service/EmitterService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/dto/AddContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/DeleteContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistCreateRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistDto.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistUpdateRequest.java
  src/main/java/team03/mopl/domain/playlist/repository/PlaylistRepository.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistService.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
  src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/team03/mopl/domain/notification/service/EmitterServiceTest.java
Labels: enhancement

#151 hotfix: build.gradle 충돌 해결
  .github/workflows/deploy.yml
  build.gradle
  ecs/task-definition.json
Labels: bug, documentation

#149 merge: main 브랜치 dev 브랜치 머지
  src/main/java/team03/mopl/common/config/CorsConfig.java
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/GlobalExceptionHandler.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentAlreadyExistsException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentEmptyException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentNotFoundForRemoveException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistContentRemoveEmptyException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistDeleteDeniedException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistDeniedException.java
  src/main/java/team03/mopl/common/exception/playlist/PlaylistUpdateDeniedException.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/dm/controller/DmController.java
  src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
  src/main/java/team03/mopl/domain/notification/service/EmitterService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/dto/AddContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/DeleteContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistCreateRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistDto.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistUpdateRequest.java
  src/main/java/team03/mopl/domain/playlist/repository/PlaylistRepository.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistService.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
  src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/team03/mopl/domain/notification/service/EmitterServiceTest.java
Labels: enhancement

#154 hotfix: 메모리 1기가로 설정 후 상태확인
  ecs/task-definition.json
Labels: enhancement

#155 hotfix: 메모리 2기가로 낮춘 뒤 상태 확인
  ecs/task-definition.json
Labels: enhancement

#158 hotfix: CPU 2GB, 메모리 2GB 로 수정 후 상태 확인
  ecs/task-definition.json
Labels: enhancement

#153 Feature/for front
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistService.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
  src/main/java/team03/mopl/domain/subscription/Subscription.java
  src/main/java/team03/mopl/domain/subscription/SubscriptionController.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
Labels: enhancement

#162 hotfix: CPU 2GB, 메모리 2GB 로 수정 후 상태 확인
  ecs/task-definition.json
Labels: enhancement

#168 chore: healthCheck command 추가
  ecs/task-definition.json
Labels: bug, documentation

#169 merge: main 브랜치로 dev 브랜치 머지
  ecs/task-definition.json
Labels: documentation

#177 chore: docker-compose.yml에 Redis, Kafka 컨테이너 추가
  build.gradle
  docker-compose.yml
Labels: documentation

#175 refactor: 로그 및 예외처리
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/auth/AuthException.java
  src/main/java/team03/mopl/common/exception/auth/InvalidPasswordException.java
  src/main/java/team03/mopl/common/exception/auth/LockedUserException.java
  src/main/java/team03/mopl/common/exception/auth/TempPasswordExpiredException.java
  src/main/java/team03/mopl/common/exception/user/DuplicatedNameException.java
  src/main/java/team03/mopl/domain/admin/AdminService.java
  src/main/java/team03/mopl/domain/auth/AuthService.java
  src/main/java/team03/mopl/domain/auth/EmailServiceImpl.java
  src/main/java/team03/mopl/domain/oauth2/CustomOAuth2UserService.java
  src/main/java/team03/mopl/domain/user/UserServiceImpl.java
  src/test/java/team03/mopl/domain/auth/AuthServiceTest.java
Labels: enhancement

#179 chore: docker compose 일부 수정
  docker-compose.yml
Labels: documentation

#180 feature: 컨텐츠 썸네일/YouTube URL 컬럼 추가 및 적재 로직 개선
  init/schema.sql
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/batch/launcher/SportsJobScheduler.java
  src/main/java/team03/mopl/domain/content/batch/launcher/TmdbJobScheduler.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsItemDto.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbApiReader.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbItemDto.java
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
  src/test/java/team03/mopl/domain/content/repository/ContentRepositoryImplTest.java
Labels: enhancement

#195 chore: application-prod.yaml redis 관련 환경 설정 추가
  src/main/resources/application-prod.yaml
Labels: documentation

#196 refactor: curation pagination, 비동기, event 처리
  init/schema.sql
  src/main/java/team03/mopl/common/config/AsyncConfig.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/InvalidCursorFormatException.java
  src/main/java/team03/mopl/common/exception/InvalidPageSizeException.java
  src/main/java/team03/mopl/common/exception/curation/ContentRatingUpdateException.java
  src/main/java/team03/mopl/common/exception/curation/InvalidScoreRangeException.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsBatchConfig.java
  src/main/java/team03/mopl/domain/content/batch/tmdb/TmdbBatchConfig.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/main/java/team03/mopl/domain/curation/CurationBatchConfig.java
  src/main/java/team03/mopl/domain/curation/CurationJobListener.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/dto/ContentWithScoreDto.java
  src/main/java/team03/mopl/domain/curation/dto/CursorPageRequest.java
  src/main/java/team03/mopl/domain/curation/entity/KeywordContent.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordContentRepository.java
  src/main/java/team03/mopl/domain/curation/service/CurationService.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
Labels: enhancement

#189 feat: 시청방 페이지네이션 구현, 코드 개선, 테스트 코드 수정 및 추가 구현 #176
  build.gradle
  init/schema.sql
  src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java
  src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomWebSocketController.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomCreateRequest.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomInfoDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomSearchDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomSearchInternalDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomWithVideoStateDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/participant/ParticipantDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/participant/ParticipantsInfoDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/video/VideoControlRequest.java
  src/main/java/team03/mopl/domain/watchroom/dto/video/VideoSyncDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/watchroommessage/WatchRoomMessageCreateRequest.java
  src/main/java/team03/mopl/domain/watchroom/dto/watchroommessage/WatchRoomMessageDto.java
  src/main/java/team03/mopl/domain/watchroom/entity/WatchRoom.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepository.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryCustom.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomMessageService.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomMessageServiceImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomService.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/watchroom/controller/WatchRoomControllerTest.java
  src/test/java/team03/mopl/domain/watchroom/controller/WatchRoomWebSocketControllerTest.java
  src/test/java/team03/mopl/domain/watchroom/handler/ChatMessageFrameHandler.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomMessageServiceImplTest.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: bug, enhancement

#187 docs: swagger
  src/main/java/team03/mopl/api/AdminApi.java
  src/main/java/team03/mopl/api/AuthApi.java
  src/main/java/team03/mopl/api/ContentApi.java
  src/main/java/team03/mopl/api/CurationApi.java
  src/main/java/team03/mopl/api/DmApi.java
  src/main/java/team03/mopl/api/DmRoomApi.java
  src/main/java/team03/mopl/api/FollowApi.java
  src/main/java/team03/mopl/api/PlaylistApi.java
  src/main/java/team03/mopl/api/ReviewApi.java
  src/main/java/team03/mopl/api/UserApi.java
  src/main/java/team03/mopl/api/WatchRoomApi.java
  src/main/java/team03/mopl/common/config/SwaggerConfig.java
  src/main/java/team03/mopl/domain/admin/AdminController.java
  src/main/java/team03/mopl/domain/admin/LockRequest.java
  src/main/java/team03/mopl/domain/admin/RoleUpdateRequest.java
  src/main/java/team03/mopl/domain/auth/AuthController.java
  src/main/java/team03/mopl/domain/auth/ChangePasswordRequest.java
  src/main/java/team03/mopl/domain/auth/LoginRequest.java
  src/main/java/team03/mopl/domain/auth/LoginResponse.java
  src/main/java/team03/mopl/domain/auth/TempPasswordRequest.java
  src/main/java/team03/mopl/domain/content/controller/ContentController.java
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
  src/main/java/team03/mopl/domain/content/dto/ContentSearchRequest.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/dto/KeywordDto.java
  src/main/java/team03/mopl/domain/curation/dto/KeywordRequest.java
  src/main/java/team03/mopl/domain/dm/controller/DmController.java
  src/main/java/team03/mopl/domain/dm/controller/DmRoomController.java
  src/main/java/team03/mopl/domain/dm/dto/DmDto.java
  src/main/java/team03/mopl/domain/dm/dto/DmRequest.java
  src/main/java/team03/mopl/domain/dm/dto/DmRoomDto.java
  src/main/java/team03/mopl/domain/follow/controller/FollowController.java
  src/main/java/team03/mopl/domain/follow/dto/FollowRequest.java
  src/main/java/team03/mopl/domain/follow/dto/FollowResponse.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationPagingDto.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/dto/AddContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/DeleteContentsRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistCreateRequest.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistDto.java
  src/main/java/team03/mopl/domain/playlist/dto/PlaylistUpdateRequest.java
  src/main/java/team03/mopl/domain/review/controller/ReviewController.java
  src/main/java/team03/mopl/domain/review/dto/ReviewCreateRequest.java
  src/main/java/team03/mopl/domain/review/dto/ReviewDto.java
  src/main/java/team03/mopl/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/team03/mopl/domain/user/Role.java
  src/main/java/team03/mopl/domain/user/UserController.java
  src/main/java/team03/mopl/domain/user/UserCreateRequest.java
  src/main/java/team03/mopl/domain/user/UserResponse.java
  src/main/java/team03/mopl/domain/user/UserUpdateRequest.java
  src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomCreateRequest.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomDto.java
Labels: documentation

#200 fix:
  src/main/java/team03/mopl/api/WatchRoomApi.java
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
  src/main/java/team03/mopl/domain/content/dto/ContentSearchRequest.java
  src/main/java/team03/mopl/domain/watchroom/controller/WatchRoomController.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomContentWithParticipantCountDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomCreateRequest.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomInfoDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/participant/ParticipantsInfoDto.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryCustom.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: bug, enhancement

#199 fix: ContentDto.java에 쉼표 추가
  src/main/java/team03/mopl/domain/content/dto/ContentDto.java
Labels: bug

#201 fix: 로그인 된 사람과 팔로우 하는 사람 동일한지 확인
  src/main/java/team03/mopl/api/FollowApi.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/follow/BadRequestFollowingException.java
  src/main/java/team03/mopl/domain/follow/controller/FollowController.java
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
  src/test/java/team03/mopl/domain/follow/controller/FollowControllerTest.java
Labels: bug

#204 refactor: 리뷰 생성, 수정, 삭제 시 content avgRating 점수 계산 event 생성
  src/main/java/team03/mopl/domain/review/event/ReviewEvent.java
  src/main/java/team03/mopl/domain/review/event/ReviewEventHandler.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
  src/test/java/team03/mopl/domain/review/ReviewServiceImplTest.java
Labels: enhancement

#209 fix: 주석 변경, reviewService transactional 추가
  src/main/java/team03/mopl/common/config/CorsConfig.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
Labels: bug

#219 refactor: 커서 페이지네이션에서 사용하는 디코더와 인코더를 공통 유틸로 분리
  src/main/java/team03/mopl/common/util/CursorCodecUtil.java
  src/main/java/team03/mopl/domain/content/service/ContentServiceImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/content/service/ContentServiceImplTest.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: enhancement

#221 chore: schema.sql 의 contents 테이블의 옵션 수정
  init/schema.sql
Labels: documentation

#228 test: 공동 유틸 관련 테스트 코드 추가
  src/main/java/team03/mopl/common/util/CursorCodecUtil.java
  src/test/java/team03/mopl/common/util/CursorCodecUtilTest.java
  src/test/java/team03/mopl/common/util/NormalizerUtilTest.java
Labels: enhancement

#233 fix: 시청방 상세 정보 누락 수정 및 로깅
  src/main/java/team03/mopl/domain/watchroom/dto/WatchRoomInfoDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/participant/ParticipantDto.java
  src/main/java/team03/mopl/domain/watchroom/dto/video/VideoControlRequest.java
  src/main/java/team03/mopl/domain/watchroom/entity/WatchRoom.java
  src/main/java/team03/mopl/domain/watchroom/exception/AlreadyJoinedWatchRoomRoomException.java
  src/main/java/team03/mopl/domain/watchroom/exception/WatchRoomException.java
  src/main/java/team03/mopl/domain/watchroom/exception/WatchRoomRoomNotFoundException.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomMessageServiceImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: bug

#226 feat: 예외 처리
  src/main/java/team03/mopl/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#230 feat: 각 도메인의 서비스 로직에 알림 기능 구현
  src/main/java/team03/mopl/common/util/CursorCodecUtil.java
  src/main/java/team03/mopl/domain/notification/NotificationEventListener.java
  src/main/java/team03/mopl/domain/notification/entity/NotificationType.java
  src/main/java/team03/mopl/domain/notification/events/FollowingPostedPlaylistEvent.java
  src/main/java/team03/mopl/domain/notification/events/PlaylistSubscribedEvent.java
  src/main/java/team03/mopl/domain/notification/events/PlaylistUpdatedEvent.java
  src/main/java/team03/mopl/domain/notification/repository/NotificationRepository.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
  src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
  src/test/java/team03/mopl/domain/notification/NotificationEventListenerTest.java
  src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
Labels: enhancement

#237 refactor: 비밀번호 패턴 적용
  src/main/java/team03/mopl/domain/user/UserController.java
  src/main/java/team03/mopl/domain/user/UserCreateRequest.java
  src/main/java/team03/mopl/domain/user/UserServiceImpl.java
  src/main/java/team03/mopl/domain/user/UserUpdateRequest.java
  src/test/java/team03/mopl/domain/user/UserControllerTest.java
  src/test/java/team03/mopl/domain/user/UserServiceImplTest.java
Labels: enhancement

#240 refactor: 스포츠 컨텐츠 데이터 적재 시간 변경, 적재 규칙 변경, 로그 위치 수정
  src/main/java/team03/mopl/domain/content/batch/launcher/SportsJobScheduler.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiProcessor.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsApiReader.java
  src/main/java/team03/mopl/domain/content/batch/sports/SportsBatchConfig.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
Labels: enhancement

#238 Bug: DmRoom 삭제 오류 수정
  init/schema.sql
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/dm/AlreadyDmRoomExistException.java
  src/main/java/team03/mopl/common/exception/dm/CannotCreateDmRoomSelfException.java
  src/main/java/team03/mopl/common/exception/dm/OutUserFromDmRoomException.java
  src/main/java/team03/mopl/domain/dm/controller/DmRoomController.java
  src/main/java/team03/mopl/domain/dm/entity/DmRoom.java
  src/main/java/team03/mopl/domain/dm/service/DmRoomService.java
  src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java
  src/test/java/team03/mopl/domain/dm/service/DmRoomServiceImplTest.java
  src/test/java/team03/mopl/domain/playlist/PlaylistServiceImplTest.java
Labels: bug

#243 test: 시청방-사용자 레포지토리 테스트 코드 구현
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java
Labels: documentation, enhancement

#235 test: subscription test code 추가
  src/test/java/team03/mopl/domain/subscription/SubscriptionControllerTest.java
  src/test/java/team03/mopl/domain/subscription/SubscriptionServiceImplTest.java
Labels: enhancement

#247 refactor: playlist 전체 조회 수정, 구독 조회 추가
  src/main/java/team03/mopl/api/PlaylistApi.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/curation/KeywordDeleteDeniedException.java
  src/main/java/team03/mopl/common/exception/subscription/PrivatePlaylistSubscriptionException.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/repository/PlaylistRepository.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistService.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
  src/main/java/team03/mopl/domain/subscription/SubscriptionRepository.java
  src/main/java/team03/mopl/domain/subscription/service/SubscriptionServiceImpl.java
  src/test/java/team03/mopl/domain/playlist/PlaylistControllerTest.java
  src/test/java/team03/mopl/domain/playlist/PlaylistServiceImplTest.java
Labels: enhancement

#248 chore: openSearch에 접근할 수 있도록 설정 추가
  ecs/task-definition.json
Labels: documentation

#252 refactor: curation elastic search 도입
  build.gradle
  docker-compose.yml
  elasticsearch/Dockerfile
  src/main/java/team03/mopl/MoplApplication.java
  src/main/java/team03/mopl/common/config/ElasticsearchConfig.java
  src/main/java/team03/mopl/common/config/ElasticsearchIndexInitializer.java
  src/main/java/team03/mopl/common/config/OpenSearchConfig.java
  src/main/java/team03/mopl/common/config/RepositoryConfig.java
  src/main/java/team03/mopl/common/config/SearchEngineConfig.java
  src/main/java/team03/mopl/common/exception/curation/KeywordAccessDeniedException.java
  src/main/java/team03/mopl/common/util/SpringApplicationContext.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/ContentChangeEvent.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
  src/main/java/team03/mopl/domain/curation/controller/CurationController.java
  src/main/java/team03/mopl/domain/curation/elasticsearch/ContentElasticsearchEventListener.java
  src/main/java/team03/mopl/domain/curation/elasticsearch/ContentSearch.java
  src/main/java/team03/mopl/domain/curation/elasticsearch/ContentSearchRepository.java
  src/main/java/team03/mopl/domain/curation/elasticsearch/ContentSearchService.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordContentRepository.java
  src/main/java/team03/mopl/domain/curation/repository/KeywordRepository.java
  src/main/java/team03/mopl/domain/curation/service/CurationService.java
  src/main/java/team03/mopl/domain/curation/service/CurationServiceImpl.java
  src/main/java/team03/mopl/domain/review/repository/ReviewRepository.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
  src/main/resources/application-prod.yaml
  src/main/resources/elasticsearch/content-mapping.json
  src/main/resources/elasticsearch/content-setting.json
  src/main/resources/elasticsearch/elasticsearch.json
  src/test/java/team03/mopl/domain/content/repository/ContentRepositoryImplTest.java
  src/test/java/team03/mopl/domain/curation/CurationControllerTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceImplTest.java
  src/test/java/team03/mopl/domain/subscription/SubscriptionServiceImplTest.java
  src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java
Labels: enhancement

#255 fix: dmService의 자신이 보낸 메시지에 대해서 읽음처리
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
Labels: enhancement

#276 feat: 채팅방에 상대방 들어와 있을 때 읽음 처리 로직 추가
  src/main/java/team03/mopl/domain/dm/controller/DmWebSocketController.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/main/java/team03/mopl/domain/dm/service/PresenceTracker.java
  src/test/java/team03/mopl/domain/dm/controller/DmWebSocketControllerTest.java
  src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java
Labels: enhancement

#279 bug: dmRoom updatedAt 필드 추가 및 최신순 정렬
  init/schema.sql
  src/main/java/team03/mopl/domain/dm/dto/DmRoomDto.java
  src/main/java/team03/mopl/domain/dm/entity/DmRoom.java
  src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/test/java/team03/mopl/domain/dm/controller/DmRoomControllerTest.java
  src/test/java/team03/mopl/domain/dm/service/DmRoomServiceImplTest.java
Labels: bug

#281 bug: dm encoding 추가
  src/main/java/team03/mopl/common/util/CursorCodecUtil.java
  src/main/java/team03/mopl/domain/dm/repository/DmRepository.java
  src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
  src/test/java/team03/mopl/domain/dm/service/DmServiceImplTest.java
Labels: bug

#282 fix: 시청방 오류, 테스트 코드 수정 및 테스트 리포트 제외 항목 추가
  build.gradle
  src/main/java/team03/mopl/common/interceptor/WebSocketAuthInterceptor.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomMessageRepository.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/common/interceptor/WebSocketAuthInterceptorTest.java
  src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java
  src/test/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImplTest.java
Labels: bug, documentation

#286 bug: dm Cursor 페이징 로직 수정
  init/schema.sql
  src/main/java/team03/mopl/domain/dm/entity/DmRoom.java
  src/main/java/team03/mopl/domain/dm/repository/DmRepositoryCustom.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/test/java/team03/mopl/domain/dm/repository/DmRepositoryCustomTest.java
Labels: bug

#290 fix: oauth 로그인 프론트 redirect url 주소 수정
  src/main/resources/application-prod.yaml
Labels: bug, documentation

#308 refactor: 빈 추가
  src/test/java/team03/mopl/domain/auth/AuthControllerTest.java
Labels: enhancement

#312 chore: Create README.md
  README.md
Labels: documentation

#317 feat: 단일 알림 읽음 처리, API 추가, 테스트 코드 추가
  src/main/java/team03/mopl/api/NotificationApi.java
  src/main/java/team03/mopl/domain/dm/service/DmRoomServiceImpl.java
  src/main/java/team03/mopl/domain/dm/service/DmServiceImpl.java
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
  src/main/java/team03/mopl/domain/notification/NotificationEventListener.java
  src/main/java/team03/mopl/domain/notification/controller/NotificationController.java
  src/main/java/team03/mopl/domain/notification/dto/NotificationDto.java
  src/main/java/team03/mopl/domain/notification/service/NotificationService.java
  src/main/java/team03/mopl/domain/notification/service/NotificationServiceImpl.java
  src/test/java/team03/mopl/domain/dm/controller/DmWebSocketControllerTest.java
  src/test/java/team03/mopl/domain/notification/controller/NotificationControllerTest.java
  src/test/java/team03/mopl/domain/notification/service/NotificationServiceImplTest.java
Labels: enhancement

#314 test: contentSearchTest 코드 생성
  src/test/java/team03/mopl/domain/curation/ContentSearchServiceTest.java
  src/test/java/team03/mopl/domain/curation/CurationServiceTest.java
Labels: enhancement

#315 refactor: 미사용 엔드포인트 제거, delete 메서드에 트랜젝션 적용
  src/main/java/team03/mopl/api/PlaylistApi.java
  src/main/java/team03/mopl/domain/playlist/controller/PlaylistController.java
  src/main/java/team03/mopl/domain/playlist/service/PlaylistServiceImpl.java
Labels: enhancement

#322 hotfix: 시청방 제목 정렬 오류 수정 및 title_nomalized 필드 추가
  init/schema.sql
  src/main/java/team03/mopl/domain/watchroom/entity/WatchRoom.java
  src/main/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/watchroom/service/WatchRoomServiceImpl.java
  src/test/java/team03/mopl/domain/watchroom/repository/WatchRoomParticipantRepositoryTest.java
  src/test/resources/sql/watchroom-test-data.sql
Labels: bug

#324 bug: notification-follow
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
Labels: bug
