Repository sb01-mopl-team03/sb01-mopl-team03, pull requests merged in 2025-06, with the labels that each got.

#18 feat: follow basic CRUD
  src/main/java/team03/mopl/domain/follow/entity/Follow.java
  src/main/java/team03/mopl/domain/follow/repository/FollowRepository.java
  src/main/java/team03/mopl/domain/follow/repository/UserRepository.java
  src/main/java/team03/mopl/domain/follow/service/FollowService.java
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
Labels: enhancement

#9 chore: GitHub Actions CI workflow 작성
  .github/test.yml
  .gitignore
  build.gradle
  build/reports/problems/problems-report.html
  gradle/wrapper/gradle-wrapper.jar
  src/main/resources/application-ci.yaml
  src/main/resources/application.properties
Labels: documentation

#14 chore: Dockerfile, docker-compose.yml 을 통한 도커 테스트 초기 환경 세팅
  Dockerfile
  docker-compose.yml
Labels: documentation

#16 feat: user crud, login(jwt)
  build.gradle
  src/main/java/team03/mopl/common/config/SecurityConfig.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/user/DuplicatedEmailException.java
  src/main/java/team03/mopl/common/exception/user/DuplicatedNameException.java
  src/main/java/team03/mopl/common/exception/user/UserException.java
  src/main/java/team03/mopl/common/exception/user/UserNotFoundException.java
  src/main/java/team03/mopl/domain/auth/AuthController.java
  src/main/java/team03/mopl/domain/auth/LoginRequest.java
  src/main/java/team03/mopl/domain/user/User.java
  src/main/java/team03/mopl/domain/user/UserController.java
  src/main/java/team03/mopl/domain/user/UserCreateRequest.java
  src/main/java/team03/mopl/domain/user/UserRepository.java
  src/main/java/team03/mopl/domain/user/UserResponse.java
  src/main/java/team03/mopl/domain/user/UserService.java
  src/main/java/team03/mopl/domain/user/UserServiceImpl.java
  src/main/java/team03/mopl/domain/user/UserUpdateRequest.java
  src/main/java/team03/mopl/jwt/CustomUserDetails.java
  src/main/java/team03/mopl/jwt/CustomUserDetailsService.java
  src/main/java/team03/mopl/jwt/JwtAuthenticationFilter.java
  src/main/java/team03/mopl/jwt/JwtProvider.java
  src/main/java/team03/mopl/jwt/JwtService.java
  src/main/java/team03/mopl/jwt/JwtServiceImpl.java
  src/main/java/team03/mopl/jwt/JwtSession.java
  src/main/java/team03/mopl/jwt/JwtSessionRepository.java
  src/test/java/team03/mopl/domain/user/UserServiceImplTest.java
Labels: enhancement

#24 fix: test.yml 을 workflows 폴더 내부로 이동
  .github/workflows/test.yml
Labels: bug, documentation

#25 feat: 콘텐츠 평가 CRUD
  Dockerfile
  build/reports/problems/problems-report.html
  init/schema.sql
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/common/exception/content/ContentException.java
  src/main/java/team03/mopl/common/exception/content/ContentNotFoundException.java
  src/main/java/team03/mopl/common/exception/review/ReviewException.java
  src/main/java/team03/mopl/common/exception/review/ReviewNotFoundException.java
  src/main/java/team03/mopl/domain/content/Content.java
  src/main/java/team03/mopl/domain/content/repository/ContentRepository.java
  src/main/java/team03/mopl/domain/follow/repository/UserRepository.java
  src/main/java/team03/mopl/domain/follow/service/FollowServiceImpl.java
  src/main/java/team03/mopl/domain/review/controller/ReviewController.java
  src/main/java/team03/mopl/domain/review/dto/ReviewCreateRequest.java
  src/main/java/team03/mopl/domain/review/dto/ReviewResponse.java
  src/main/java/team03/mopl/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/team03/mopl/domain/review/entity/Review.java
  src/main/java/team03/mopl/domain/review/repository/ReviewRepository.java
  src/main/java/team03/mopl/domain/review/service/ReviewService.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
Labels: enhancement

#31 refactor: ReviewCreateRequest 수정, follow.userRepository 삭제
  src/main/java/team03/mopl/domain/follow/repository/UserRepository.java
  src/main/java/team03/mopl/domain/review/dto/ReviewCreateRequest.java
  src/main/java/team03/mopl/domain/review/service/ReviewServiceImpl.java
Labels: bug

#38 feat: 채팅방 생성 및 조회 기능 구현 및 환경 설정
  .gitignore
  build.gradle
  src/main/java/team03/mopl/common/config/QueryDslConfig.java
  src/main/java/team03/mopl/common/exception/ErrorCode.java
  src/main/java/team03/mopl/domain/chat/controller/ChatRoomController.java
  src/main/java/team03/mopl/domain/chat/dto/ChatRoomContentWithHeadcountDto.java
  src/main/java/team03/mopl/domain/chat/dto/ChatRoomDto.java
  src/main/java/team03/mopl/domain/chat/exception/AlreadyJoinedChatRoomException.java
  src/main/java/team03/mopl/domain/chat/repository/ChatRoomParticipantRepository.java
  src/main/java/team03/mopl/domain/chat/repository/ChatRoomParticipantRepositoryCustom.java
  src/main/java/team03/mopl/domain/chat/repository/ChatRoomParticipantRepositoryImpl.java
  src/main/java/team03/mopl/domain/chat/service/ChatRoomService.java
  src/main/java/team03/mopl/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/team03/mopl/domain/content/ContentRepository.java
  src/test/java/team03/mopl/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/team03/mopl/domain/chat/performance/ChatRoomPerformanceTest.java
  src/test/java/team03/mopl/domain/chat/service/ChatRoomServiceImplTest.java
Labels: enhancement
